### PR TITLE
hostname was getting set to the puppet master's fqdn in my case...

### PR DESCRIPTION
**Pull request by mrisher**
I did find what seemed to be a bug… The resource file your program generated for me had the "hostname" parameter set to the puppet master, rather than the node, i.e. I had node like

```
<node name="events1003.impermium.com" 
    type="Node"
    description="events1003.impermium.com"
    …
    hostname="puppet.impermium.com"
/>
```

It was the same for all my nodes.

When I changed the following line from `facts.values["fqdn"]` to just `n.name`, it resolved the problem for me, but I assume this bug was due to a misconfiguration on my end rather than yours...

### CODE REVIEW

**Comment by jamtur01** [comment]
This is quite odd because it should be pulling the fact values for the node NOT the master.  Are any of of the other fact values wrong, i.e. belong to the master not the node?

**Comment by lrhazi** [comment]
I have this same issue. I get the XML with all the nodes. The nodes have the same attributes, except for "name" which is correct, everything else is the same. For example osName is RedHat, though I have many Solaris.

**Comment by jamtur01** [comment]
Hmmm looks like the fact merge is broken. I'll take a look tonight hopefully.

**Comment by jamtur01** [comment]
Fixed in 0.0.6.

**Pull request closed without merging**
